language: java

addons:
  sonarcloud:
    organization: "dumb-code"
    token:
      secure: "oDArfd/3Py/DqO2A8+2yYamhQkggksj6iUGkBkXDbvAFPIUhxgDXGayrp5YXdCwRltnsjRpgPcb2Hv1h/57QGmnN37xIfTMqffX09qdOG023QXrCofGrnIzBUmjRxixTiTI+aFcxNBBCVe4P6vGBd5dSB8Aed1Bbqf4MPnMvSSPr620SIVHztXQZX5jWjZNlPkGRLVHco28TQzSsDt/V5d2vni4IMfmThlleApyjp3mBs8DgD9sXgZp4MNDjml5zzBU3NZ1gBz70XoenablwgVf8SzRbrzK5qDVuJ6ktbbAJi7hyl42rQ/LMc5sgFvZpHHS9if/pMyFVT17p71wFsczy/IBgYGvJU/AWzr1zVWxk5rRbplHrwlBFwr+4p3lhf0rFK9m1yvkkvHIDe0II5OyubGQKZVcu1XxY5h9GXQnUHInX7aQJpTtQW6L+mXjMc8ge++4qC4kemidEEbAsAh/YcYmPv3Petxo7UWV4m2RfXSW4dhfQYcQZdhrM4igkguLuXOrvDQ4p0G/toqm6RI3mt0dr3BGas3XENIv/gJhc9oBqryafgKg9x0RqzLx+3SRe1f6Nffap54c28WLuuBzJ/B+mQECli1AWsenz14iJ8i97ovigqDtvQ3t0fZnqCK2rD720OB5TkiCRRonkmWos48ioz008qlGptw+OKGU="

jdk:
  - oraclejdk8
  
dist: trusty

before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - "git fetch --unshallow"
  
install:
  - true

script:
  - "./gradlew postRequest"
  - "./gradlew sonarqube"

after_failure:
  - "./gradlew notifyIfError"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

env:
  global:
    - secure: "hOTg4kPUqj6qG7LweJdmVzYiRYyXg6r/jX5WQa1ni3YiBYVl91+KIl57DhBz5bEKM+L3pJ4uX3bUHTqwoqlixzmIrT6s/z2Ab/enm54a9Ot8belhv5NeTg+7OMKxsdPyEznY2OFEhiBD6JxN2+/OPzfa23X2CFqE9nJPOYDoa1dkDjKkeSZxFx6Sf4ye2dWchg++OGrYsRad4J5C4suLkGbnzk5UC60wWh+vL771Qa8l8adk2cXJlBJJxWSvEtK/hfmH+F7zKxyU/jT6nLLpJrJLaQc4iWqdMo8GV2FWMIcmSs5wEDTwZ/KZiA4dhX2ZQIR11b5yJ/W+ce390EtmZ46ZuT7dxoxC3L5bmMFMvOLCv7WQVJk01JEikWnHD2IMgkfhUYYo99Y/MD9bajfAYEs1A8nk06f3h8kLoXnVoZjDpteouDzTsp6D7pXgIr/D6Z4ohvfsA1j8lnUZH2S6lOc6PpLljpJUVqx9zUOiTd7EhIqaZoBG79jJJ5udphEScFshESeXOz3o8BTT7MYyIUscKWiBtqNNFpIzDQagNfMWjk+EJT22Hg/kU6k8fKmgedoBbtdfXHU7VJE2FUx0iAx2dtXXTgHTS+OloqeN9A8W6rtDGhztqo4/oX+9dxJhRic9QiSCr8GgLkCkNwEQ89estWgQ0s0naD9k7hLWbxU="
