language: java
addons:
  sonarcloud:
    organization: dumb-code
    token:
      secure: oDArfd/3Py/DqO2A8+2yYamhQkggksj6iUGkBkXDbvAFPIUhxgDXGayrp5YXdCwRltnsjRpgPcb2Hv1h/57QGmnN37xIfTMqffX09qdOG023QXrCofGrnIzBUmjRxixTiTI+aFcxNBBCVe4P6vGBd5dSB8Aed1Bbqf4MPnMvSSPr620SIVHztXQZX5jWjZNlPkGRLVHco28TQzSsDt/V5d2vni4IMfmThlleApyjp3mBs8DgD9sXgZp4MNDjml5zzBU3NZ1gBz70XoenablwgVf8SzRbrzK5qDVuJ6ktbbAJi7hyl42rQ/LMc5sgFvZpHHS9if/pMyFVT17p71wFsczy/IBgYGvJU/AWzr1zVWxk5rRbplHrwlBFwr+4p3lhf0rFK9m1yvkkvHIDe0II5OyubGQKZVcu1XxY5h9GXQnUHInX7aQJpTtQW6L+mXjMc8ge++4qC4kemidEEbAsAh/YcYmPv3Petxo7UWV4m2RfXSW4dhfQYcQZdhrM4igkguLuXOrvDQ4p0G/toqm6RI3mt0dr3BGas3XENIv/gJhc9oBqryafgKg9x0RqzLx+3SRe1f6Nffap54c28WLuuBzJ/B+mQECli1AWsenz14iJ8i97ovigqDtvQ3t0fZnqCK2rD720OB5TkiCRRonkmWos48ioz008qlGptw+OKGU=
jdk:
  - oraclejdk8
dist: trusty
before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - git fetch --unshallow
install:
  - true
script:
  - "./gradlew postRequest -x :dumb_library:postRequest -x :dumb_library:javadoc --no-daemon"
  - "./gradlew sonarqube"
after_failure:
  - "./gradlew notifyIfError -x :dumb_library:notifyIfError"
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"
env:
  global:
    - secure: GHxKEKEs4kA3GSe0chc3/Gswxtgjejuvx6W/JnZEgXtgAaNBWbOdLSqR7hwv9du3jj3q7tmxdA7sSiCGizX0RWXhwEUg0BIr5hsmJ0Rmslmnjxi85N3cNunCsr8BCCsGmJ7Cxr3JT0C919OORMU90JnuGU+Lb4xN7K9XWPTmpV9Q/y0aCynx6Ev9c5f4927wdAXodhWVVg1qmqH1O8fUfaVirpaVtjnTWUYFxpyEX8GiNLUzdTj+TSjbc1egc6ioXUIwanMjnnuOTkGOgsNcUx/Kfunm2/dGbL/af7ornDkmRduQ2RAMLBFIsk9Wmx0ODe8I8Qg4yog/zbkFGdwGjyeBGQsv8ZbTfOW2Z0X2B/xme83us2wO5mr0i4b14Ds5zgSc5/BieDH7YioGmiiK9+q3ID2pwuLHx6VjzserIlixzEUgF7dY857bkOX7z6Onon0hYU7XyWscv1O8ZLOOpNik+cJJwjDY2Gl0YzdHFQ9lcPT4qNquKH/jcHIrRbKQfEPKYDGV63suCgLX4S6xQwL4yMWEF17bz5kITST9R60pHoGzfzvswsxcHOHDGpA5ChtBIw+B9xKo8Ik7YpBIA3PCMALiaePccHjl+mplYEeYAB7Y96r3nuqXrEBy8DaEFLd7a5TwVFr4gCMIyZKwf/TevCLgJmTbpGwnZTALtH8=
