language: java
addons:
  sonarcloud:
    organization: dumb-code
    token:
      secure: oDArfd/3Py/DqO2A8+2yYamhQkggksj6iUGkBkXDbvAFPIUhxgDXGayrp5YXdCwRltnsjRpgPcb2Hv1h/57QGmnN37xIfTMqffX09qdOG023QXrCofGrnIzBUmjRxixTiTI+aFcxNBBCVe4P6vGBd5dSB8Aed1Bbqf4MPnMvSSPr620SIVHztXQZX5jWjZNlPkGRLVHco28TQzSsDt/V5d2vni4IMfmThlleApyjp3mBs8DgD9sXgZp4MNDjml5zzBU3NZ1gBz70XoenablwgVf8SzRbrzK5qDVuJ6ktbbAJi7hyl42rQ/LMc5sgFvZpHHS9if/pMyFVT17p71wFsczy/IBgYGvJU/AWzr1zVWxk5rRbplHrwlBFwr+4p3lhf0rFK9m1yvkkvHIDe0II5OyubGQKZVcu1XxY5h9GXQnUHInX7aQJpTtQW6L+mXjMc8ge++4qC4kemidEEbAsAh/YcYmPv3Petxo7UWV4m2RfXSW4dhfQYcQZdhrM4igkguLuXOrvDQ4p0G/toqm6RI3mt0dr3BGas3XENIv/gJhc9oBqryafgKg9x0RqzLx+3SRe1f6Nffap54c28WLuuBzJ/B+mQECli1AWsenz14iJ8i97ovigqDtvQ3t0fZnqCK2rD720OB5TkiCRRonkmWos48ioz008qlGptw+OKGU=
jdk:
  - oraclejdk8
dist: trusty
before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - git fetch --unshallow
install:
  - true
script:
  - "./gradlew postRequest -x :dumb_library:postRequest -x :dumb_library:javadoc --no-daemon"
  - "./gradlew sonarqube"
after_failure:
  - "./gradlew notifyIfError -x :dumb_library:notifyIfError"
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"
env:
  global:
    - secure: T05k0BaSV1BCJ328lItPy+QgDSfkodZShhJ7AKeIAzujsopkys/aiTMLTWYwZxsZEL/B5kVZ9DCo8q318JxmYQPS8rQ6IUs3sXABnnafr+OYfDqHisv7+T26orAYhP+SJKgl42NN4OUIPOgsVRpyy+qB938HVdlGCxMXqU6p3EZxFX0TyYaRH8FTwWxjzGDrDUJavIJSsNrvTC96S3+oDM6jo0YA0lSDHO1sZYeNk0gFCmdtz7zgPMC/MGaUH4zjwvB7iXtVXnm+QrOq86sqtGSvwarPcRErTfi8oC+oKjd1AXTc3udXh+XnNZpwf3fmUgDf0SZ7NVxn1GpkrmRze0hksK1hHKZzplvwn9x2pV55Vm8bTOK7rw3OqYnXGgio6Awzgg8ZBq6vkmMHIU9mt1d81vItDPP6XOQ4QSRCbyOyrofDKIWMoyiNZGQg71H6hTivZk9KJ+imZq5erq5yEHgHxTVNb4M/b74SSNkhS7Nlc70XPcnIWmq/z4A3lBVz4TGOOS5PbO26r7m5YxpvQRQEet0ZRV9l8OQ3haR3eOa6Zv8t99rlgQeQhxWcgZhsl/jCmghBOmMLYCu7JP20snt1ySHxrlnNeoPwbehzUIxTJwXuiee41tEwr8Nl19WAybN7AeFLaEbRGuUwwx2/K0dtfMxkQa3p864IzwTNFrY=
