language: java
addons:
  sonarcloud:
    organization: dumb-code
    token:
      secure: AoqiIGevYlpBFvfcSpXvqne3hWX9H3byvlk41F9oMn8D4ocYgX2dEkUuWde+qzt3ROd3usQMSDbsnRKFXI3ZiRRoPZ/7rntqBgMd1AESn+QG7a/QtQ++arc/
      PMS2xCq1YRWhWjhixVe26+kh4cP9GHqtQYjdck9EacjN7Szkwf3kOR1ihKTZP8JUOBJVJfYqO5qvLWZcKwBHc0mMh3MXHIMQYInbWnr5VVk6blnlrprNtIxzLXRpfPOu6D5
      Dp0WBRGS8r/yle+ZBFkpljJLa/Fyz4KV42XpHKoxINz6Xe6+ioI+kPonQJEw5XqGOgBS/cWZAcuo91ZEtpHUkPZPcq2ulwFYJE8ebHeB2Gw+YmI4u5+Q619hNCooGp1H7kv
      CIj16ZsdKuzGEf2IWkaDAaOv6EhhfSUefJAG2elCoLtYJdLLHAL0Z27Z+mczyHiih94hLGpg+5ykccikpZ1EQTGxUhaY90utLYgvkBx/IjNSbDK4dGcY7Jju/58Z3U2xJA7
      jsP7IS75h3HlZ0iA6+a2K13Qfuh4kgY6TjCf9stK6/rsR6xpK7a/GQPCUFNlJfTXjF1jq3yw+ZD1fMReVJPHBhkE9fv3N2EK8aaId0jiziu9lL/ELteimVbSOElAT9KOtOl
      TPvFMQx3J9gg8wXxq9c6GIMlfXtf1ZKVpoYWH/8=
jdk:
  - oraclejdk8
dist: trusty
before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - git fetch --unshallow
install:
  - true
script:
  - "./gradlew postRequest -x :dumb_library:postRequest"
  - "./gradlew sonarqube"
after_failure:
  - "./gradlew notifyIfError -x :dumb_library:notifyIfError"
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"
env:
  global:
    - secure: T05k0BaSV1BCJ328lItPy+QgDSfkodZShhJ7AKeIAzujsopkys/aiTMLTWYwZxsZEL/B5kVZ9DCo8q318JxmYQPS8rQ6IUs3sXABnnafr+OYfDqHisv7+T26orAYhP+SJKgl42NN4OUIPOgsVRpyy+qB938HVdlGCxMXqU6p3EZxFX0TyYaRH8FTwWxjzGDrDUJavIJSsNrvTC96S3+oDM6jo0YA0lSDHO1sZYeNk0gFCmdtz7zgPMC/MGaUH4zjwvB7iXtVXnm+QrOq86sqtGSvwarPcRErTfi8oC+oKjd1AXTc3udXh+XnNZpwf3fmUgDf0SZ7NVxn1GpkrmRze0hksK1hHKZzplvwn9x2pV55Vm8bTOK7rw3OqYnXGgio6Awzgg8ZBq6vkmMHIU9mt1d81vItDPP6XOQ4QSRCbyOyrofDKIWMoyiNZGQg71H6hTivZk9KJ+imZq5erq5yEHgHxTVNb4M/b74SSNkhS7Nlc70XPcnIWmq/z4A3lBVz4TGOOS5PbO26r7m5YxpvQRQEet0ZRV9l8OQ3haR3eOa6Zv8t99rlgQeQhxWcgZhsl/jCmghBOmMLYCu7JP20snt1ySHxrlnNeoPwbehzUIxTJwXuiee41tEwr8Nl19WAybN7AeFLaEbRGuUwwx2/K0dtfMxkQa3p864IzwTNFrY=
