language: java
addons:
  sonarcloud:
    organization: dumb-code
    token:
      secure: AoqiIGevYlpBFvfcSpXvqne3hWX9H3byvlk41F9oMn8D4ocYgX2dEkUuWde+qzt3ROd3usQMSDbsnRKFXI3ZiRRoPZ/7rntqBgMd1AESn+QG7a/QtQ++arc/PMS2xCq1YRWhWjhixVe26+kh4cP9GHqtQYjdck9EacjN7Szkwf3kOR1ihKTZP8JUOBJVJfYqO5qvLWZcKwBHc0mMh3MXHIMQYInbWnr5VVk6blnlrprNtIxzLXRpfPOu6D5Dp0WBRGS8r/yle+ZBFkpljJLa/Fyz4KV42XpHKoxINz6Xe6+ioI+kPonQJEw5XqGOgBS/cWZAcuo91ZEtpHUkPZPcq2ulwFYJE8ebHeB2Gw+YmI4u5+Q619hNCooGp1H7kvCIj16ZsdKuzGEf2IWkaDAaOv6EhhfSUefJAG2elCoLtYJdLLHAL0Z27Z+mczyHiih94hLGpg+5ykccikpZ1EQTGxUhaY90utLYgvkBx/IjNSbDK4dGcY7Jju/58Z3U2xJA7jsP7IS75h3HlZ0iA6+a2K13Qfuh4kgY6TjCf9stK6/rsR6xpK7a/GQPCUFNlJfTXjF1jq3yw+ZD1fMReVJPHBhkE9fv3N2EK8aaId0jiziu9lL/ELteimVbSOElAT9KOtOlTPvFMQx3J9gg8wXxq9c6GIMlfXtf1ZKVpoYWH/8=
jdk:
  - oraclejdk8
dist: trusty
before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - git fetch --unshallow
install:
  - true
script:
  - "./gradlew postRequest -x :dumb_library:postRequest -x :dumb_library:javadoc -x javadoc"
  - "./gradlew sonarqube -x :dumb_library:javadoc -x javadoc"
after_failure:
  - "./gradlew notifyIfError -x :dumb_library:notifyIfError"
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"

env:
  global:
    - secure: aNOwECan+Yg5luRQnMbbU0RYrb95Ox/VfsUz8sYthYqMMWd6aGJC+4ZppgGRzpSOXBm3/UcrNGJhtEiMOErq82Wgvx+9uDYRaMIJa4GE4/tTFkysbFV0ck+54KE6H6s0FPSbQ0gHj7m/Go1PTke2HBFn9plWE72jwv7N/Z466scuCz6fNggw/+E2aC9m87pifFzc9ALAKzVX6fTGGbrpIcelOonHLOc7iHM9Zkpg01ybkafrbyf9r3DeVXf/1O6fgMqcWmFilMrLLHLNOsyA04s5mAGy6aNr6kjPZPvpnb27/f8ogXvARJCMNRkfxU2Pu7QTA5Q5qAvPKuaGoc5xlVabg/BXCmAzO7nrMoi0UZWYLa/rZROV3/MKDUgW+TfZxzxe35mIwb0KzodOSGI99mLgOOmRMNsikYQhB0iMf4PH1bmb70XMQaS+N5VG3m4hd56iUY4zClJ5eTumGNm194HiHkC4c7Cm3M0fNet4OiQXMawqKuZDddwcQYts0iAdblgaU5/NqEHJKedxFEDKp/t7WfpvibAiJY2yDdQkluQvM0W0Omh+zz66oDVdYIGHjKqL3dWfZwxhRsNiFk4nFHPJ6baUZphj27Og5vqIVVYYht+cTwjoGbYUn4zxaThw4ByBTy2UthrHde25RMbbFHBjg15rbdw22Mq8UJo5f60=
