language: java

addons:
  sonarcloud:
    organization: "dumb-code"
    token:
      secure: oDArfd/3Py/DqO2A8+2yYamhQkggksj6iUGkBkXDbvAFPIUhxgDXGayrp5YXdCwRltnsjRpgPcb2Hv1h/57QGmnN37xIfTMqffX09qdOG023QXrCofGrnIzBUmjRxixTiTI+aFcxNBBCVe4P6vGBd5dSB8Aed1Bbqf4MPnMvSSPr620SIVHztXQZX5jWjZNlPkGRLVHco28TQzSsDt/V5d2vni4IMfmThlleApyjp3mBs8DgD9sXgZp4MNDjml5zzBU3NZ1gBz70XoenablwgVf8SzRbrzK5qDVuJ6ktbbAJi7hyl42rQ/LMc5sgFvZpHHS9if/pMyFVT17p71wFsczy/IBgYGvJU/AWzr1zVWxk5rRbplHrwlBFwr+4p3lhf0rFK9m1yvkkvHIDe0II5OyubGQKZVcu1XxY5h9GXQnUHInX7aQJpTtQW6L+mXjMc8ge++4qC4kemidEEbAsAh/YcYmPv3Petxo7UWV4m2RfXSW4dhfQYcQZdhrM4igkguLuXOrvDQ4p0G/toqm6RI3mt0dr3BGas3XENIv/gJhc9oBqryafgKg9x0RqzLx+3SRe1f6Nffap54c28WLuuBzJ/B+mQECli1AWsenz14iJ8i97ovigqDtvQ3t0fZnqCK2rD720OB5TkiCRRonkmWos48ioz008qlGptw+OKGU=

jdk:
  - oraclejdk8

dist: trusty

before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - "git fetch --unshallow"

install:
  - true

script:
  - "./gradlew postRequest"
  - "./gradlew sonarqube"

after_failure:
  - "./gradlew notifyIfError"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

env:
  global:
    - secure: evRohqMGfqXJ+FLLb3E+n2eoM7//VB7IsUfqMBKq2lJWWazWIB9g5xB185/rdAy3W19IuVxyq+DVQidbiyb249uLzvYQsk42PPdE8jd8aGTwfXfpdSqgnhjamJYQuhve5jDeF/fZFxz/ds/fZ8s9t2toAKcGEdbZRw3Xyd8WJ+BOZGjnr0YdZUmA6NjMiJZ5di71/litWe1bu+L+6GRDHuMqMkg/LKXgodklFOTdxHLqOokj76LslodmqoLu/zrk9Aog8h0W8okftommFbBclKtDtdxRrIr4YQLQNMZ6A3wS6RuWVd7jmqzDr9pLm4BwMf64TBxpk8Loh3eLBNgNBPZb6RiRtXSF6QoM8FRCOQGNiDNeZU8LswHeKDCS7h7/DEJJ4HmJJ437FXMv2sb+ZWxaM4Ox0MJp69wi1fLdi+wtTf1P7HB2x5O2RKbEtJyOaWToUeEhNqPSrLfgwKKsnlmHm/1eRdeSFXzToXhD/kRqkXOvZXSxMvRJ30zVzhiUH35aEgv0KW/nPcTDqUepkTzJTLmgRP8ZRJwlJKSyqodmsrdO+MPaFL5ornfPKnEWtFh/wBX8BRgtBPp2hXJJd+0dZ8NvawvCRwSwTgNp2na+ZWeUwevkVkxB6+rpY3RQajzUSHrUQAtD3kjqC/i2a4QCUZTZlVYlJPOGzmnpFdA=