language: java

addons:
  sonarcloud:
    organization: "dumb-code"
    token:
      secure: "oDArfd/3Py/DqO2A8+2yYamhQkggksj6iUGkBkXDbvAFPIUhxgDXGayrp5YXdCwRltnsjRpgPcb2Hv1h/57QGmnN37xIfTMqffX09qdOG023QXrCofGrnIzBUmjRxixTiTI+aFcxNBBCVe4P6vGBd5dSB8Aed1Bbqf4MPnMvSSPr620SIVHztXQZX5jWjZNlPkGRLVHco28TQzSsDt/V5d2vni4IMfmThlleApyjp3mBs8DgD9sXgZp4MNDjml5zzBU3NZ1gBz70XoenablwgVf8SzRbrzK5qDVuJ6ktbbAJi7hyl42rQ/LMc5sgFvZpHHS9if/pMyFVT17p71wFsczy/IBgYGvJU/AWzr1zVWxk5rRbplHrwlBFwr+4p3lhf0rFK9m1yvkkvHIDe0II5OyubGQKZVcu1XxY5h9GXQnUHInX7aQJpTtQW6L+mXjMc8ge++4qC4kemidEEbAsAh/YcYmPv3Petxo7UWV4m2RfXSW4dhfQYcQZdhrM4igkguLuXOrvDQ4p0G/toqm6RI3mt0dr3BGas3XENIv/gJhc9oBqryafgKg9x0RqzLx+3SRe1f6Nffap54c28WLuuBzJ/B+mQECli1AWsenz14iJ8i97ovigqDtvQ3t0fZnqCK2rD720OB5TkiCRRonkmWos48ioz008qlGptw+OKGU="

jdk:
  - oraclejdk8
  
dist: trusty

before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
  - "git fetch --unshallow"
  
install:
  - true

script:
  - "./gradlew postRequest"
  - "./gradlew sonarqube"

after_failure:
  - "./gradlew notifyIfError"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

env:
  global:
    - secure: "WnoOXbD2O1ozbEhhkHTNt8x7w527+75cN+b8GgkHMDUq5S53gmiAheBe26VdOiwCJ/npd7XySufyTvlwKyHcCPd9pFUMd6NRzxyKJpYoI16/EWVsQuzuK8DBF/6b0uOXAMK3YgzkRQGrulRLPNNKyn3PTC/V9s43MqOfBJ7R9cSQ5SCYVcKt7r/L9aIG4/KAn3xMRjuDBiaYj8H3ikLf6Yeka+jZcSwCMEqhmBcbEnpAvuaxjxIUqffF9JOa6yENDTAJBHl+r+BxvPmnpZhAWVk3jPOR96JV5PE4YMSwYEVLm3KJSZ6j5sjTT/v+VMFmWP6dUfzTlPxCwVXiwucsXGDO1Df/JAoRPTGCYqCmK5ih7/QoLm4r5eRjl4aFXvhUEg1AeKgXM4huOggpBBlF59ZicMsWdFHjBtJpiWHSbY5LDTSIV+FgYizjk2KZSlFdeZEQTOHV3wW8tR6bJl+vMgy4J0bYw1J5puHfOFYx15RoV6LMdb1ONCCFe8iILSirfxYNkGp+PGP+QtTuVqxwgqlIJwqoJgFwOe4r39nAY87cvIjR4isy/HHJXACZjfkh1KGmhddw8wG38yGhwcT/QFbiFOdtsazRs6erfxpY+jNILPFSD37VKFZ3dAy3rrS3KgCeGDQskGkhPvS+JLYbGdIv76XINfoC6L8yXL2PopY="
